version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Generate config
          command: |
            node ./scripts/ci/generate.js
      - continuation/continue:
          configuration_path: .circleci/config.generated.yml

workflows:
  setup:
    jobs:
      - setup