on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]

name: All Checks
jobs:
  install:
    name: Insall dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: |
            scripts/yarn.lock
            code/yarn.lock
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          yarn task --task install --start-from=never --no-link --debug
          git diff --exit-code
