on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]

name: All Checks
jobs:
  build:
    name: Insall dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the Yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          yarn config get cacheFolder
          echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('scripts/yarn.lock') }}-${{ hashFiles('code/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-
            ${{ runner.os }}-yarn-v1-${{ hashFiles('scripts/yarn.lock') }}-

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          yarn task --task install --start-from install --debug
          git diff --exit-code

      - name: Debug
        run: |
          ls ${{ steps.yarn-cache-dir-path.outputs.dir }}

      - name: compile
        run: |
          yarn task --task compile --start-from=compile --no-link --debug
          git diff --exit-code
