on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]

name: All Checks
jobs:
  compile:
    name: Prepare dependencies and compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: ~/.yarn/berry/cache
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('scripts/yarn.lock') }}-${{ hashFiles('code/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-
            ${{ runner.os }}-yarn-v1-${{ hashFiles('scripts/yarn.lock') }}-

      - name: Install Dependencies
        run: |
          yarn task --task install --start-from install --debug
          git diff --exit-code

      - name: Compile
        run: |
          yarn task --task compile --start-from=compile --no-link --debug
          git diff --exit-code

      - name: Cache Verdacio
        uses: actions/cache@v3
        with:
          path: .verdaccio-cache
          key: ${{ runner.os }}-verdaccio-v1

      - name: Publish to Verdaccio
        working-directory: code
        run: yarn local-registry --publish
