on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]

name: All Checks
jobs:
  compile:
    name: Prepare dependencies and compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache Yarn and Playwright
        id: dependency-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn/berry/cache
            ~/.cache/ms-playwright
            code/node_modules
            scripts/node_modules
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('scripts/yarn.lock') }}-${{ hashFiles('code/yarn.lock') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-
            ${{ runner.os }}-yarn-v1-${{ hashFiles('scripts/yarn.lock') }}-
            ${{ runner.os }}-yarn-v1-${{ hashFiles('scripts/yarn.lock') }}-${{ hashFiles('code/yarn.lock') }}-

      - name: Install Dependencies
        run: |
          yarn task --task install --start-from install --debug
          git diff --exit-code

      # TODO: See if playwright container is faster than this
      - name: Install Playwright Browsers
        if: steps.dependency-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Install Playwright Dependencies
        if: steps.dependency-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps
  
      - name: Compile
        run: |
          yarn task --task compile --start-from=compile --no-link --debug
          git diff --exit-code

      # - name: Cache Verdacio
      #   uses: actions/cache@v3
      #   with:
      #     path: .verdaccio-cache
      #     key: ${{ runner.os }}-verdaccio-v1

      - name: Publish to Verdaccio
        working-directory: code
        run: yarn local-registry --publish

  create-sandboxes:
    name: Create Sandboxes
    runs-on: ubuntu-latest
    needs: compile
    strategy:
      matrix:
        template: [react-vite/default-ts, angular-cli/default-ts]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Restore dependnecy cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.yarn/berry/cache
            ~/.cache/ms-playwright
            code/node_modules
            scripts/node_modules
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('scripts/yarn.lock') }}-${{ hashFiles('code/yarn.lock') }}-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Compile
        run: |
          yarn task --task compile --start-from=compile --no-link --debug
          git diff --exit-code

      - name: Restore Verdaccio cache
        uses: actions/cache/restore@v3
        with:
          path: .verdaccio-cache
          key: ${{ runner.os }}-verdaccio-v1
          fail-on-cache-miss: true

      - name: 'Create Sandbox: ${{ matrix.template }}'
        run: yarn task --task sandbox --template ${{ matrix.template }} --no-link --start-from=never --junit
