name: Markdown Links Check
# runs every monday at 9 am
on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:
  # To test fixes on push rather than wait for the scheduling, do the following:
  # 1. Uncomment the lines below and add your branch.
  push:
    branches:
      - chore/link-checker
  # 2. 👉 DON'T FORGET TO COMMENT OUT THE CODE BACK BEFORE YOU MERGE YOUR CHANGES!

jobs:
  check-links:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        # checks all markdown files from important folders including all subfolders
        with:
          # only show errors that occur instead of successful links + errors
          # use-quiet-mode: 'yes'
          # output full HTTP info for broken links
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/markdown-link-check-config.json'
