name: Prepare prerelease PR
run-name: Prepare prerelease PR, triggered by ${{ github.triggering_actor }}

on:
  push:
    branches:
      - main-v2
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Which release type to use for bumping the version'
        required: true
        default: 'prerelease'
        type: choice
        options:
          - prerelease
          - prepatch
          - preminor
          - premajor
          - patch
          - minor
          - major
      pre-id:
        description: For prerelease versions, what prerelease identifier to use, eg. 'alpha', 'beta', 'rc'
        required: false
        type: string

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1

jobs:
  prepare-prerelease-pull-request:
    name: Prepare prerelease pull request
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts
    steps:
      - name: Checkout main-v2
        uses: actions/checkout@v3
        with:
          ref: main-v2
          # this needs to be set to a high enough number that it will contain the last version tag
          # as of May 2023, the whole repo has 55K commits
          fetch-depth: 10000

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn/berry/cache
          key: yarn-v1-${{ hashFiles('scripts/yarn.lock') }}

      - name: Install Script Dependencies
        run: |
          yarn install

      - name: Check if pull request is frozen
        id: check-frozen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./node_modules/.bin/ts-node --swc ./release/is-pr-frozen.ts

      # TODO: check if a version bump is needed, skip next two steps if not

      - name: Bump version
        id: version
        run: |
          yarn release:version --release-type ${{ inputs.release-type || 'prerelease' }} ${{ inputs.pre-id && format('{0} {1}', '--pre-id', inputs.pre-id) }} --verbose

      - name: Write changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn release:write-changelog ${{ steps.version.outputs.next-version }} --verbose

      # TODO: generate PR description

      - name: Create or update pull request
        if: steps.check-frozen.outputs.frozen == 'false' || github.event_name == 'workflow_dispatch'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'bump version to ${{ steps.version.outputs.next-version }}'
          title: 'Bump version to ${{ steps.version.outputs.next-version }}'
          body: |
            This is an automated pull request to bump the version from ${{ steps.version.outputs.current-version }} to ${{ steps.version.outputs.next-version }}.
            Please review and merge this pull request to release the new version.
          branch: version-from-${{ steps.version.outputs.current-version }}
          base: main-v2-release
          draft: false
          delete-branch: true
